### ISSUE TITLE
Make script editor shortcuts more accessible

### ISSUE THREAD

**Issue by imagejan** [scijava/script-editor#18]
The <kbd>Ctrl</kbd>+<kbd>/</kbd> (<kbd>⌘</kbd>+<kbd>/</kbd> on Mac) shortcut is useful for (un-)commenting out a line of code. Let's make it more discoverable:

* Include a menu command *Comment/Uncomment line* with an explanatory label *Ctrl-/*
* Include a button in the UI (?)
* Also support <kbd>Ctrl</kbd>+<kbd>#</kbd> to be able to use this from other than US keyboard layouts (?)

---

For other Eclipse-like shortcuts (like e.g. <kbd>Ctrl</kbd>+<kbd>D</kbd> to delete an entire line), we should also provide menu commands with shortcut labels.

**Comment by etarena** [comment]
Do such shortcuts apply to IJ1 Macro language scripts?  There was [a recent question](https://forum.image.sc/t/toggle-commenting-out-ijm-code-in-script-editor/24749) posted on the forum regarding this... would it be possible to extend such functionality to the IJ1 Macro language as well?

**Comment by ctrueden** [comment]
@etarena The `ImageJMacroTokenMaker` was missing the method implementation defining how line commenting should work. I added it, so the shortcut works now.

@imagejan This shortcut is one of many supported directly by the RSyntaxTextArea library. I do not know what effect adding those commands to the menu would have, but I would speculate it would create multiple events handling the same key sequence, which might result in incorrect behavior. Someone would need to dig into RSyntaxTextArea to identify the best way to achieve what you want here.

**Comment by imagejan** [comment]
Don't have time to investigate more just now, but for the record, the keyboard shortcut is registered [here in `RSyntaxTextAreaDefaultInputMap`](https://github.com/bobbylight/RSyntaxTextArea/blob/b09b966d9f09e869ec14a43ef63d95f575bb2e1d/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/RSyntaxTextAreaDefaultInputMap.java#L59).

**Comment by tferr** [comment]
With v7.0.1 there has been a cleanup of shortcuts (to fix conflicts between RSyntaxTextArea and our own), and there is a Help>List shortcuts menu that lists (hopefully all) registered hotkeys
