### ISSUE TITLE
getBoolean from PrefService does not work in Jython 

### ISSUE THREAD

**Issue by Jindil** [scijava/script-editor#19]
This was pointed on the [forum](http://forum.imagej.net/t/setting-persistence-for-parameters-of-genericdialog-in-jython/10814/12?u=lthomas) by @imagejan 

```python
#@ PrefService prefs

retrievedValue = prefs.getBoolean(None, "persistedBool", False)
retrievedString = prefs.get(None, "persistedString", "abcdefghijklmnopqrstuvwxyz")

print retrievedValue # always prints False
print retrievedString

prefs.put(None, "persistedBool", not retrievedValue)
prefs.put(None, "persistedString", retrievedString[0:-1])
```
While it works with getInt
```python
#@ PrefService prefs

retrievedValue = prefs.getInt(None, "persistedBool", False) # <-- see change here
retrievedString = prefs.get(None, "persistedString", "abcdefghijklmnopqrstuvwxyz")

print retrievedValue # now it works as expected
print retrievedString

prefs.put(None, "persistedBool", not retrievedValue)
prefs.put(None, "persistedString", retrievedString[0:-1])
```

**Comment by imagejan** [comment]
That's a Python/Jython limitation. `True` and `False` are simply `1` and `0` in Java, and will therefore be treated as `int`s when trying to match overloaded Java methods.

The only solution I see would be to rename the `put` methods in `PrefService` to `putBoolean` and `putInt` to avoid overloading altogether. But that's only one of many places where overloaded methods are used, and Jython simply doesn't play well with them...

**Comment by ctrueden** [comment]
See [jython issue #1781](http://bugs.jython.org/issue1781). There is a workaround given there:
```python
from java.lang import Boolean
prefs.put(None, "persistedBool", Boolean(not retrievedValue))
```
And maybe some day, this will be fixed in Jython 3.x.
