### ISSUE TITLE
Bug with integer persistence and default value

### ISSUE THREAD

**Issue by Jindil** [scijava/script-editor#25]
I noticed that the persistence set up an unexpected value (actually 0) when the value entered by the user is the one defined as default.

ex:
```python
#@ int (label="delta", min=-5, value=10) delta 
print delta
```
The persisted value is indeed recovered in every case, except if the user enters 10, then the next time the script is launched the value is 0 !

Tested on 2 different fiji installations, with Jython and the IJ macro language.

Associated [post](https://forum.image.sc/t/bug-with-integer-persistence-and-default-value/20428) on the forum

**Comment by Jindil** [comment]
It works fine with `Integer` though

**Comment by imagejan** [comment]
Thanks @Jindil for reporting, and sorry for the delayed reply.

I'm closing this in favor of these two issues in `scijava-common`:
 * https://github.com/scijava/scijava-common/issues/302
 * https://github.com/scijava/scijava-common/issues/303
